### ISSUE TITLE
0.1.0

### ISSUE THREAD

**Issue by fuyukaidesu** [gtorrent/gtorrent-gtk#6]
<a href="https://github.com/nyanpasu"><img src="https://avatars.githubusercontent.com/u/6234817?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nyanpasu](https://github.com/nyanpasu)**
_Wednesday Jul 16, 2014 at 18:25 GMT_
_Originally opened as https://github.com/gtorrent/gTorrent-legacy/issues/41_

---

The following list is _almost_ done. Right now I'm polishing the rough edges. But I still am accepting suggestions to add to the list.

If you feel like a feature should belong in #70 feel free to move it there or comment down here if you can't.
## Features
- [x] [**Options that can be set at runtime:**](https://github.com/gtorrent/gTorrent/issues/79)
  - [x] Throttling torrent specific upload/download rate
- [x] [**Configuration files**](https://github.com/gtorrent/gTorrent/issues/59)
  - [x] Download location
  - [x] Set global throttle upload/download rate
  - [x] Torrent properties
- [ ] [**Grouping torrents**](https://github.com/gtorrent/gTorrent/issues/60)
  - [ ] Start/stop by group
  - [ ] Set group settings (throttles, max peers etc.)
  - [ ] Save to <groupname_dir>/<torrentname_dir>
- [x] [**Visible torrent states**](https://github.com/gtorrent/gTorrent/issues/61)
  - [ ] Icons (Unconfirmed)
  - [x] Start 
  - [x] Paused
  - [x] Initializing
- [ ] [**Right click menus**](https://github.com/gtorrent/gTorrent/issues/80)
  - [x] View properties
  - [ ] Options to load
- [x] [**Dragging features**](https://github.com/gtorrent/gTorrent/issues/74)
  - [x] Drag a torrent file to load it **if** it hasn't already been loaded
  - [x] Drag a highlighted magnet link to load it **if** it hasn't already been loaded
- [x] [**Columns**](https://github.com/gtorrent/gTorrent/issues/63)
  - [x] _Choose what columns you want visible or not_ (Needs more details)
  - [x] ETA
  - [x] Seed ratio
  - [x] Up speed
  - [x] Status [Uninitialized/Downloading/Seeding/Complete]
- [ ] [**Sort torrents**](https://github.com/gtorrent/gTorrent/issues/81)
  - [x] By dragging
  - [ ] With right-click menu
  - [x] Sorting by columns (Implicit?)
  - [x] Allow manual rearranging
- [ ] [Multiple viewing methods](https://github.com/gtorrent/gTorrent/issues/66) (**i.e:** List, grid, etc.)
- [x] [Torrent properties](https://github.com/gtorrent/gTorrent/issues/68)
- [x] [Session state](https://github.com/gtorrent/gTorrent/issues/69)
- [x] Add stop/pause (Worked on. See 'pause' branch)
- [ ] [DHT support](https://github.com/gtorrent/gTorrent/issues/78) (libtorrent-rasterbar supports this.)
- [ ] [Torrent priorities](https://github.com/gtorrent/gTorrent/issues/76)
- [x] [Cross platform home directory](https://github.com/gtorrent/gTorrent/issues/77)
- [x] [Choose an icon :^)](http://4chan.org/g/gtorrent)
- [ ] Error dialogs
## Bug fixes

Added incrementally as they are found.
- [x] [Invalid magnet links and files crashing](https://github.com/gtorrent/gTorrent/issues/75)
## Other TODOs
- [x] Work on more flags for cmake
  - [x] Debug mode
  - [x] Enable/Disable console screen on Windows
- [ ] Distributable binaries for Windows
- [ ] .deb package files for Debian/Ubuntu
## Notes

To prevent features getting their own special unique 0.0.X, it's much better if you make a PR to a branch _just_ for your own feature, so that when we do increment 0.0.X we can do it together with a bunch of other features that have _also_ been confirmed to work.

**Notes:** Please try to work on this issues on a separate branch so that you can create partial PRs for other people to test before we actually merge it into master. When we merge into master the following should be done:
- Increment version 0.0.X in CMakeLists.txt
- Update CHANGELOG with features added in that version
